server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websiteHealthBook
    username: root
    password: 112233
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: api/v1

jwt:
  expirationMs: 2592000 #30 days = 30*24*60*60
  secret: 8qICZqQST7dv0aFih0oxEXvvzxtfg5eZ8AP326+Db70=


